# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'OCAndJSDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OCAndJSDemo
  pod 'WebViewJavascriptBridge'

  target 'OCAndJSDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OCAndJSDemoUITests' do
    # Pods for testing
  end

end
